import {useEffect,useRef,useState,type ReactNode} from 'react';
import {en,vi,errors} from './i18n';
import {call,clearSession} from './service';
import {MAX_FILE} from './crypto/bytes';
import type {PDFVerification} from './crypto/pdf';
type KeyInfo={publicPem:string;fingerprint:string;bits:number;hasPrivate:boolean;certificate:string};
type Artifact={url:string;name:string;kind:'signature'|'pdf'|'public'|'private'|'certificate'};
type Result={kind:'signed'|'verified';valid:boolean;fingerprint:string;fingerprintMatches?:boolean;pdf?:PDFVerification[]};
type IconName='sign'|'verify'|'key'|'shield'|'file'|'upload'|'download'|'arrow'|'check'|'close'|'sun'|'moon'|'copy'|'lock'|'info'|'external';
function Icon({name,size=20}:{name:IconName;size?:number}) {
  const paths:Record<IconName,ReactNode>={
    sign:<><path d="m14 4 6 6M4 20l4-1L21 6a2.1 2.1 0 0 0-3-3L5 16l-1 4Z"/><path d="M13 20h7"/></>,
    verify:<><path d="M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="m9 11 3 3L21 4"/></>,
    key:<><circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-4-4 3-3m-6 0 3-3"/></>,
    shield:<><path d="M12 3 3 7v5c0 5 9 9 9 9s9-4 9-9V7l-9-4Z"/><path d="m8 12 3 3 5-6"/></>,
    file:<><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></>,
    upload:<><path d="M12 16V3m-5 5 5-5 5 5M3 16v4a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-4"/></>,
    download:<><path d="M12 3v13m-5-5 5 5 5-5M3 16v4a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-4"/></>,
    arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,check:<path d="m5 12 4 4L19 6"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,
    sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/></>,
    moon:<path d="M21 13A9 9 0 0 1 11 3a9 9 0 1 0 10 10Z"/>,
    copy:<><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h4"/></>,
    lock:<><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/></>,
    info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/></>,
    external:<><path d="M14 3h7v7m0-7L10 14M10 3H4a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1v-6"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function FilePicker({file,onChange,title,hint,accept,t,disabled=false}:{file:File|null;onChange:(file:File|null)=>void;title:string;hint?:string;accept?:string;t:typeof en;disabled?:boolean}) {
  const [drag,setDrag]=useState(false);
  return <div className="field"><span className="field-label">{title}</span><label className={`dropzone ${file?'selected':''} ${drag?'dragging':''} ${hint?'compact':''}`} onDragOver={e=>{e.preventDefault();if(!disabled)setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!disabled&&e.dataTransfer.files[0])onChange(e.dataTransfer.files[0]);}}>
    <input type="file" accept={accept} aria-label={title} disabled={disabled} onChange={e=>{onChange(e.target.files?.[0]??null);e.target.value='';}}/>
    <span className="file-icon"><Icon name={file?'file':'upload'} size={hint?22:28}/></span>
    <strong>{file?file.name:hint||t.drop}</strong><span>{file?`${(file.size/1024).toLocaleString(undefined,{maximumFractionDigits:1})} KiB`:t.dropSmall}</span>
    {!file&&!hint&&<span className="choose-pill">{t.choose}<Icon name="arrow" size={15}/></span>}
  </label>{file?<button className="text-button small" type="button" disabled={disabled} onClick={()=>onChange(null)}><Icon name="close" size={13}/>{t.remove}</button>:<small className="muted">{t.limit}</small>}</div>;
}
function Panel({title,description,children,className=''}:{title:string;description?:string;children:ReactNode;className?:string}) {
  return <section className={`panel ${className}`}><div className="panel-heading"><h2>{title}</h2>{description&&<p>{description}</p>}</div>{children}</section>;
}
const safePreference=(key:string,fallback:string)=>{try{return localStorage.getItem(key)||fallback;}catch{return fallback;}};
export default function App() {
  const [lang,setLang]=useState<'vi'|'en'>(()=>safePreference('rsa-language','vi')==='en'?'en':'vi');const t=lang==='vi'?vi:en;
  const [theme,setTheme]=useState(()=>{const x=safePreference('rsa-theme','system');return ['light','dark','system'].includes(x)?x:'system';});
  const [tab,setTab]=useState<'keys'|'sign'|'verify'>(()=>['keys','verify'].includes(location.hash.slice(1))?location.hash.slice(1) as 'keys'|'verify':'sign');
  const [mode,setMode]=useState<'detached'|'pdf'>('detached');const [keys,setKeys]=useState<KeyInfo|null>(null);
  const [file,setFile]=useState<File|null>(null),[sigFile,setSigFile]=useState<File|null>(null);
  const [verifyPem,setVerifyPem]=useState(''),[importPem,setImportPem]=useState(''),[importPassword,setImportPassword]=useState('');
  const [bits,setBits]=useState(3072),[certPem,setCertPem]=useState(''),[certName,setCertName]=useState('');
  const [exportMode,setExportMode]=useState('encrypted'),[exportPassword,setExportPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState('');
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState<keyof typeof en|null>(null);
  const [result,setResult]=useState<Result|null>(null),[artifacts,setArtifacts]=useState<Artifact[]>([]);
  const urls=useRef(new Set<string>()),epoch=useRef(0);
  const supported=!!crypto?.subtle&&window.isSecureContext;
  useEffect(()=>{
    const query=matchMedia('(prefers-color-scheme: dark)');const update=()=>{document.documentElement.dataset.theme=theme==='system'?(query.matches?'dark':'light'):theme;};update();query.addEventListener('change',update);
    try{localStorage.setItem('rsa-theme',theme);}catch{}return ()=>query.removeEventListener('change',update);
  },[theme]);
  useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('rsa-language',lang);}catch{}},[lang]);
  useEffect(()=>{const listener=()=>{const value=location.hash.slice(1);if(['keys','sign','verify'].includes(value)){setTab(value as typeof tab);setResult(null);setError('');}};window.addEventListener('hashchange',listener);return ()=>window.removeEventListener('hashchange',listener);},[]);
  useEffect(()=>()=>{clearSession();for(const url of urls.current)URL.revokeObjectURL(url);},[]);
  const changeTab=(value:typeof tab)=>{setTab(value);location.hash=value;setResult(null);setError('');setNotice(null);};
  const discardResult=()=>{setResult(null);setError('');setNotice(null);setArtifacts(old=>{for(const a of old){URL.revokeObjectURL(a.url);urls.current.delete(a.url);}return [];});};
  const chooseFile=(value:File|null)=>{discardResult();if(value&&value.size>MAX_FILE){setFile(null);setError('SIZE');return;}setFile(value);};
  const addArtifact=(data:string|ArrayBuffer,name:string,kind:Artifact['kind'])=>{const url=URL.createObjectURL(new Blob([data],{type:kind==='pdf'?'application/pdf':kind==='signature'?'application/json':'application/x-pem-file'}));urls.current.add(url);setArtifacts(old=>{const removed=old.filter(a=>a.kind===kind);for(const a of removed){URL.revokeObjectURL(a.url);urls.current.delete(a.url);}return [...old.filter(a=>a.kind!==kind),{url,name,kind}];});};
  const run=async(task:()=>Promise<void>)=>{const generation=epoch.current;setBusy(true);setError('');setNotice(null);try{await task();}catch(e){if(generation===epoch.current&&e instanceof Error&&e.message!=='CANCELLED')setError(e.message);}finally{if(generation===epoch.current)setBusy(false);}};
  const reset=()=>{epoch.current++;clearSession();setKeys(null);setFile(null);setSigFile(null);setVerifyPem('');setImportPem('');setImportPassword('');setCertPem('');setCertName('');setExportPassword('');setConfirmPassword('');setResult(null);setError('');setNotice(null);setBusy(false);for(const url of urls.current)URL.revokeObjectURL(url);urls.current.clear();setArtifacts([]);};
  const loadText=async(file:File|undefined,setter:(value:string)=>void)=>{if(!file)return;if(file.size>1024*1024){setError('SIZE');return;}try{setter(await file.text());discardResult();}catch{setError('FORMAT');}};
  const adopt=(value:KeyInfo)=>{setKeys(value);discardResult();setExportPassword('');setConfirmPassword('');};
  const sign=()=>run(async()=>{if(!file)return;const output=await call('sign',{data:await file.arrayBuffer(),mode});addArtifact(mode==='pdf'?output:JSON.stringify(output,null,2),`${file.name}.${mode==='pdf'?'signed.pdf':'signature.json'}`,mode==='pdf'?'pdf':'signature');setResult({kind:'signed',valid:true,fingerprint:keys!.fingerprint});});
  const verify=()=>run(async()=>{if(!file)return;const output=await call('verify',{data:await file.arrayBuffer(),mode,signature:sigFile?await sigFile.text():'',pem:verifyPem});if(mode==='pdf'){const pdf=output as PDFVerification[];setResult({kind:'verified',valid:pdf.every(x=>x.valid),fingerprint:pdf[0].fingerprint,pdf});}else setResult({kind:'verified',...output});});
  const errorText=errors[error]?.[lang==='vi'?0:1]||errors.UNKNOWN[lang==='vi'?0:1];
  const artifactLabel=(kind:Artifact['kind'])=>({signature:t.downloadSig,pdf:t.downloadPDF,public:t.downloadPublic,private:t.downloadPrivate,certificate:t.downloadCert}[kind]);
  const downloads=<div className="downloads">{artifacts.filter(a=>tab==='keys'?['public','private','certificate'].includes(a.kind):['signature','pdf','public'].includes(a.kind)).map(a=><a key={a.kind} className="button secondary" href={a.url} download={a.name}><Icon name="download" size={17}/>{artifactLabel(a.kind)}</a>)}</div>;
  const fingerprint=<div className="fingerprint"><span>{t.fingerprint}</span><code>{keys?.fingerprint.match(/.{1,4}/g)?.join(' ')}</code><button className="icon-button" type="button" title={t.copy} aria-label={t.copy} onClick={()=>run(async()=>{await navigator.clipboard.writeText(keys!.fingerprint);setNotice('copied');})}><Icon name="copy" size={16}/></button></div>;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#sign" onClick={()=>changeTab('sign')}><span className="brand-icon"><Icon name="shield" size={25}/></span><span>RSA<span className="brand-light"> Studio</span><small>DOCUMENT INTEGRITY</small></span></a>
      <div className="nav-label">{t.workspace}</div><nav aria-label={t.workspace}>{(['sign','verify','keys'] as const).map(item=><button key={item} className={`nav-item ${tab===item?'active':''}`} onClick={()=>changeTab(item)}><Icon name={item==='keys'?'key':item}/><span>{t[item]}</span>{tab===item&&<span className="nav-dot"/>}</button>)}</nav>
      <div className="session-card"><span className="eyebrow">{t.session}</span><div className="session-state"><span className={`status-dot ${keys?'ready':''}`}/>{keys?(keys.hasPrivate?t.privateReady:t.publicReady):t.noKey}</div>{keys&&<span className="mono session-bits">RSA {keys.bits} / SHA-256</span>}<button className="text-button" onClick={reset} disabled={!keys&&!file&&!busy&&!importPem&&!verifyPem}><Icon name="close" size={14}/>{t.clear}</button></div>
      <div className="sidebar-bottom"><div className="local-note"><Icon name="lock" size={17}/><span>{t.local}</span></div><div className="preferences"><label><span className="sr-only">{t.theme}</span><Icon name={theme==='dark'?'moon':'sun'} size={16}/><select value={theme} onChange={e=>setTheme(e.target.value)} aria-label={t.theme}><option value="system">{t.system}</option><option value="light">{t.light}</option><option value="dark">{t.dark}</option></select></label><label><span className="sr-only">{t.language}</span><select value={lang} onChange={e=>setLang(e.target.value as typeof lang)} aria-label={t.language}><option value="vi">VI</option><option value="en">EN</option></select></label></div></div>
    </aside>
    <main><header className="topbar"><span className="breadcrumb">{t.app}<span>/</span><strong>{t[tab]}</strong></span><div className="topbar-actions"><button className="text-button mobile-clear" onClick={reset} disabled={!keys&&!file&&!busy&&!importPem&&!verifyPem}>{t.clear}</button><span className="profile-pill"><span className="status-dot ready"/>{t.security}</span></div></header>
      <div className="content"><div className="page-heading"><div><span className="eyebrow blue">{tab==='keys'?'RSA KEY PAIR':tab==='sign'?'SIGN & SHARE':'VERIFY & INSPECT'}</span><h1>{t[`${tab}Title` as keyof typeof en]}</h1><p>{t[`${tab}Intro` as keyof typeof en]}</p></div><div className="heading-symbol"><Icon name={tab==='keys'?'key':tab} size={38}/></div></div>
        {!supported&&<div role="alert" className="alert error">{errors.WORKER[lang==='vi'?0:1]}</div>}
        {error&&<div role="alert" className="alert error"><Icon name="info"/>{errorText}</div>}{notice&&<div role="status" className="alert success"><Icon name="check"/>{t[notice]}</div>}
        {busy&&<div role="status" className="processing"><span className="spinner"/>{t.working}</div>}
        {tab==='keys'?<>
          <div className="keys-grid"><Panel title={t.newKeys} description={t.newKeysHint}><div className="key-illustration"><Icon name="key" size={44}/><span>RSA</span><span className="mono">e = 65537</span></div><label className="field"><span className="field-label">{t.size}</span><select value={bits} onChange={e=>setBits(Number(e.target.value))} disabled={busy}>{[2048,3072,4096].map(n=><option key={n} value={n}>{n} bit{n===3072?` · ${t.recommended}`:''}</option>)}</select></label><button className="button primary full" disabled={busy||!supported} onClick={()=>run(async()=>{adopt(await call('generate',{bits}));setNotice('keyCreated');})}><Icon name="key" size={18}/>{t.create}<Icon name="arrow" size={17}/></button></Panel>
          <Panel title={t.importTitle} description={t.importHint}><label className="field"><span className="field-label">{t.pemLabel}</span><textarea value={importPem} onChange={e=>setImportPem(e.target.value)} placeholder="-----BEGIN PRIVATE KEY-----" spellCheck={false} autoComplete="off" disabled={busy}/></label><label className="file-button"><Icon name="upload" size={15}/>{t.keyFile}<input type="file" accept=".pem,.key,.txt" disabled={busy} onChange={e=>{void loadText(e.target.files?.[0],setImportPem);e.target.value='';}}/></label><label className="field"><span className="field-label">{t.importPassword}</span><input type="password" value={importPassword} autoComplete="off" disabled={busy} onChange={e=>setImportPassword(e.target.value)} placeholder={t.password}/></label><button className="button secondary full" disabled={busy||!importPem.trim()||!supported} onClick={()=>run(async()=>{adopt(await call('import',{pem:importPem,password:importPassword}));setImportPem('');setImportPassword('');setNotice('keyImported');})}>{t.importAction}<Icon name="arrow" size={17}/></button></Panel></div>
          {keys&&<Panel title={t.active} description={t.keepSafe}><div className="active-key-row"><span className="key-badge"><Icon name="key"/>RSA {keys.bits}</span><span className="state-label"><span className="status-dot ready"/>{keys.hasPrivate?t.privateReady:t.publicReady}</span><button className="button secondary" disabled={busy} onClick={()=>addArtifact(keys.publicPem,'rsa-public.pem','public')}><Icon name="download" size={17}/>{t.downloadPublic}</button></div>{fingerprint}
            {keys.hasPrivate&&<div className="key-details-grid"><div><h3>{t.exportTitle}</h3><div className="segmented"><button className={exportMode==='encrypted'?'active':''} disabled={busy} onClick={()=>setExportMode('encrypted')}>{t.encrypted}</button><button className={exportMode==='plain'?'active':''} disabled={busy} onClick={()=>setExportMode('plain')}>{t.plaintext}</button></div>{exportMode==='encrypted'?<><label className="field"><span className="field-label">{t.exportPassword}</span><input type="password" value={exportPassword} autoComplete="new-password" disabled={busy} onChange={e=>setExportPassword(e.target.value)}/></label><label className="field"><span className="field-label">{t.confirmPassword}</span><input type="password" value={confirmPassword} autoComplete="new-password" disabled={busy} onChange={e=>setConfirmPassword(e.target.value)}/></label></>:<p className="warning-text">{t.plaintextWarning}</p>}<button className="button secondary" disabled={busy} onClick={()=>run(async()=>{if(exportMode==='encrypted'&&exportPassword.length<12)throw Error('PASSWORD_LENGTH');if(exportMode==='encrypted'&&exportPassword!==confirmPassword)throw Error('PASSWORD_CONFIRM');const output=await call('exportPrivate',{password:exportMode==='encrypted'?exportPassword:''});addArtifact(output,exportMode==='encrypted'?'rsa-private-encrypted.pem':'rsa-private.pem','private');setExportPassword('');setConfirmPassword('');})}><Icon name="download" size={17}/>{t.exportAction}</button></div>
            <div><h3>{t.certTitle}</h3><p className="muted small">{t.certIntro}</p><label className="field"><span className="field-label">{t.certName}</span><input value={certName} maxLength={200} disabled={busy} onChange={e=>setCertName(e.target.value)}/></label><button className="button secondary" disabled={busy||!certName.trim()} onClick={()=>run(async()=>{adopt(await call('createCertificate',{name:certName}));setNotice('certCreated');})}>{t.createCert}</button><label className="field"><span className="field-label">{t.certPem}</span><textarea value={certPem} onChange={e=>setCertPem(e.target.value)} placeholder="-----BEGIN CERTIFICATE-----" spellCheck={false} disabled={busy}/></label><label className="file-button"><Icon name="upload" size={15}/>{t.keyFile}<input type="file" accept=".pem,.crt,.cer" disabled={busy} onChange={e=>{void loadText(e.target.files?.[0],setCertPem);e.target.value='';}}/></label><button className="button secondary" disabled={busy||!certPem.trim()} onClick={()=>run(async()=>{adopt(await call('certificate',{pem:certPem}));setCertPem('');setNotice('certImported');})}>{t.importCert}</button>{keys.certificate&&<div className="cert-ready"><span><Icon name="check" size={16}/>{t.certLoaded}</span><button className="text-button" onClick={()=>addArtifact(keys.certificate,'rsa-certificate.pem','certificate')}>{t.downloadCert}<Icon name="download" size={14}/></button></div>}<p className="muted small">{t.selfSigned}</p></div></div>}{downloads}</Panel>}
        </>:<>
          <div className="format-tabs" role="group" aria-label={t.algorithm}>{(['detached','pdf'] as const).map(value=><button key={value} className={mode===value?'active':''} disabled={busy} onClick={()=>{setMode(value);discardResult();}}><Icon name={value==='pdf'?'file':'sign'} size={20}/><span><strong>{t[value]}</strong><small>{t[value==='pdf'?'pdfHint':'detachedHint']}</small></span><span className="radio-mark"/></button>)}</div>
          <div className="operation-grid"><Panel title={t.document} className="document-panel"><FilePicker title={t.document} file={file} onChange={chooseFile} accept={mode==='pdf'?'.pdf':undefined} t={t} disabled={busy}/>
            {tab==='verify'&&mode==='detached'&&<><FilePicker title={t.signatureFile} file={sigFile} onChange={value=>{discardResult();if(value&&value.size>16384){setSigFile(null);setError('SIZE');return;}setSigFile(value);}} accept=".json" hint={t.signatureHint} t={t} disabled={busy}/><label className="field"><span className="field-label">{t.publicKey}</span><textarea value={verifyPem} onChange={e=>{setVerifyPem(e.target.value);discardResult();}} spellCheck={false} placeholder={t.publicHint} disabled={busy}/></label><label className="file-button"><Icon name="upload" size={15}/>{t.keyFile}<input type="file" accept=".pem,.crt,.cer" disabled={busy} onChange={e=>{void loadText(e.target.files?.[0],setVerifyPem);e.target.value='';}}/></label></>}
            {mode==='pdf'&&<p className="muted small pdf-limit">{t.unsupportedPDF}</p>}
            <div className="action-line"><span><Icon name="lock" size={14}/>{t.local}</span><button className="button primary" disabled={busy||!supported||!file||(tab==='sign'&&(!keys?.hasPrivate||(mode==='pdf'&&!keys.certificate)))||(tab==='verify'&&mode==='detached'&&(!sigFile||!verifyPem.trim()))} onClick={tab==='sign'?sign:verify}><Icon name={tab==='sign'?'sign':'verify'} size={18}/>{tab==='sign'?t.signAction:t.verifyAction}<Icon name="arrow" size={17}/></button></div>
          </Panel><div className="operation-aside"><Panel title={tab==='sign'?t.signingKey:t.algorithm}>
              {tab==='sign'?<>{keys?.hasPrivate?<><div className="key-badge"><Icon name="key"/>RSA {keys.bits}</div>{fingerprint}{mode==='pdf'&&<p className={keys.certificate?'state-label':'warning-text'}>{keys.certificate?t.certLoaded:t.certNeeded}</p>}</>:<div className="empty-key"><Icon name="key" size={29}/><p>{t.needed}</p></div>}<button className="text-button" disabled={busy} onClick={()=>changeTab('keys')}>{t.goKeys}<Icon name="arrow" size={15}/></button></>:<div className="algorithm-stack"><span>RSA-PSS</span><span>SHA-256</span><span>MGF1 · 32-byte salt</span></div>}
              <div className="aside-profile"><span>{t.algorithm}</span><strong>RSA-PSS / SHA-256</strong><small>MGF1-SHA-256 · salt 32 B</small></div></Panel><div className="next-note"><Icon name="info" size={18}/><h3>{t.next}</h3><p>{tab==='verify'?t.nextVerify:mode==='pdf'?t.nextPDF:t.nextSign}</p></div></div></div>
          <section className={`record ${result?(result.valid?(result.pdf?.some(p=>p.modifiedAfterSigning)?'record-warning':'record-valid'):'record-invalid'):''}`} aria-live="polite"><div className="record-header"><span className="eyebrow">{t.result}</span><span className="mono">RSA / SHA-256</span></div>{result?<><div className="result-title"><span className="result-icon"><Icon name={result.valid?'check':'close'} size={25}/></span><div><h2>{result.kind==='signed'?t.generated:result.valid?(result.pdf?.some(p=>p.modifiedAfterSigning)?t.earlierRevision:t.verified):t.invalid}</h2><p>{result.kind==='signed'?t[mode==='pdf'?'nextPDF':'nextSign']:result.valid?(result.pdf?.some(p=>p.modifiedAfterSigning)?t.modifiedDetail:t.validDetail):t.invalidDetail}</p></div></div>
            <div className="record-chain">{[{icon:'file',label:t.docRecord,value:file?.name??'',status:result.valid?t.signed:t.loaded},{icon:'sign',label:t.sigRecord,value:mode==='pdf'?t.pdf:t.detached,status:result.valid?t.match:t.mismatch},{icon:'key',label:t.keyRecord,value:result.fingerprint.match(/.{1,8}/g)?.join(' ')??'',status:result.valid?t.match:t.mismatch}].map((item,i)=><div className="chain-item" key={i}><Icon name={item.icon as IconName} size={22}/><span>{item.label}<strong className={i===2?'mono':''}>{item.value}</strong></span><small>{item.status}</small></div>)}</div>
            {result.fingerprintMatches===false&&<p className="warning-text">{t.fingerprintWarning}</p>}
            {result.pdf?.map((pdf,i)=><div key={i} className="pdf-result"><h3>{t.signatureFile} {i+1} · {pdf.valid?t.match:t.mismatch}</h3><dl><div><dt>{t.signer}</dt><dd>{pdf.name}</dd></div><div><dt>{t.algorithm}</dt><dd>{pdf.algorithm}</dd></div><div><dt>{t.coverage}</dt><dd>{pdf.coveredBytes.toLocaleString()} / {pdf.totalBytes.toLocaleString()}</dd></div><div><dt>{t.certificate}</dt><dd>{pdf.certificateStatus==='current'?t.current:pdf.certificateStatus==='expired'?t.expired:t.notYet}</dd></div><div><dt>{t.fingerprint}</dt><dd className="mono">{pdf.fingerprint}</dd></div></dl>{pdf.modifiedAfterSigning&&<div className="alert warning"><div><strong>{t.modified}</strong><p>{t.modifiedDetail}</p></div></div>}</div>)}
            {downloads}<div className="trust-note"><Icon name="info" size={17}/><div><strong>{t.identity}</strong><p>{t.identityDetail}</p></div></div>
          </>:<div className="empty-record"><div className="mini-chain"><Icon name="file"/><span/><Icon name="sign"/><span/><Icon name="key"/></div><h3>{t.noResult}</h3><p>{t.noResultHint}</p></div>}</section>
        </>}
        <div className="bottom-notes"><details><summary><Icon name="shield" size={17}/>{t.fips}<span>+</span></summary><p>{t.fipsDetail} <a href="https://csrc.nist.gov/pubs/fips/186-5/final" target="_blank" rel="noreferrer">NIST FIPS 186-5 <Icon name="external" size={12}/></a></p></details><details><summary><Icon name="lock" size={17}/>{t.privacy}<span>+</span></summary><p>{t.privacyDetail}</p></details><details><summary><Icon name="info" size={17}/>{t.guide}<span>+</span></summary><p>{t.guideText}</p></details></div>
        <footer><span>RSA Studio <span className="footer-dot">·</span> {t.tagline}</span><span>{t.local}</span></footer>
      </div>
    </main>
  </div>;
}
